name: Lint nix

on:
  workflow_call:

permissions: {}

jobs:
  nixpkgs-fmt:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: actions/checkout@v5.0.0
      - name: Check formatting
        run: |
          nix run --inputs-from . nixpkgs#nixpkgs-fmt -- --check .

  statix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: actions/checkout@v5.0.0
      - name: Static code analysis
        run: |
          nix run --inputs-from . nixpkgs#statix -- check . -i test/highlighting-examples.nix

  deadnix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: DeterminateSystems/nix-installer-action@v21
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: actions/checkout@v5.0.0
      - name: Check for dead code
        run: |
          nix run --inputs-from . nixpkgs#deadnix -- -f --exclude test/highlighting-examples.nix

